AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  app

  Sample SAM Template for app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    MemorySize: 512

Resources:
  CalculatorFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: CalculatorFunction
      Handler: calculator.CalculatorHandler::handleRequest  # Ensure this matches the actual class name
      Runtime: java21
      Architectures:
        - x86_64
      MemorySize: 512
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins:
            - "*"
          AllowMethods:
            - "POST"
            - "GET"
          AllowHeaders:
            - "content-type"
          MaxAge: 300
      


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CalculatorFunction:
    Description: "Calculator Lambda Function ARN"
    Value: !GetAtt CalculatorFunction.Arn
  CalculatorFunctionIamRole:
    Description: "Implicit IAM Role created for Calculator function"
    Value: !GetAtt CalculatorFunctionRole.Arn
  FunctionUrl:
    Description: "URL for Function"
    Value: !GetAtt CalculatorFunctionUrl.FunctionUrl
